### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KK09123** [SerenityS/kakaobot_hyoammeal#1]
(myvenv) ubuntu@ubuntu-VirtualBox:~/Project$ python3 manage.py runserver host-ip:8000
Performing system checks...

System check identified no issues (0 silenced).
July 20, 2017 - 21:32:52
Django version 1.11.3, using settings 'kakaobot.settings'
Starting development server at http://host-ip:8000/
Quit the server with CONTROL-C.
Error: [Errno -2] Name or service not known

어디 부분이 문제인가요??

**Comment by SerenityS** [comment]
Hostip에 본인ip넣으셔야 합니다.

**Comment by KK09123** [comment]
(myvenv) ubuntu@ubuntu-VirtualBox:~/Test1$ python3 manage.py runserver host-ip:122.xx.xxx.xx
CommandError: "host-ip:122.xx.xxx.xx" is not a valid port number or address:port pair.
x는 아이피 가린거 입니다. 공유기 사용 중인데 이번엔 어딘가 문제 일까요?
 답변 감사드립니다.

**Comment by SerenityS** [comment]
host-ip를 지우세요..
