### ISSUE TITLE
/kakaobot/settings.py 에 시크릿키 유출되어있는것 같습니다.

### ISSUE THREAD

**Issue by cokia** [SerenityS/kakaobot_hyoammeal#4]
카카오톡 봇에서 사용하는 시크릿키가 /kakaobot/settings.py 
경로에 적혀있습니다. 삭제하시는게 좋을듯합니다 ^^

**Comment by SerenityS** [comment]
레포는 그냥 커밋 업로드용이고 실사용은 따로 있어요~~
그래도 조언 감사합니다^^ 리드미에 추가해야겠네요

**Comment by cokia** [comment]
네엡~~
